services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app/api
    # user: 1000:100
    # volumes:
    #   - ./api:/app/api
    #   - ./classlibrary:/app/classlibrary
    environment:
      - NODE_ID=1
      - OTHER_NODES=2,http://node2:5000;3,http://node3:5000
      - NODE_INTERVAL=50
    command: dotnet watch --project raft-luris26.csproj
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - "5001:5000"
    networks:
      - raft_network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app/api
    # user: 1000:100
    # volumes:
    #   - ./api:/app/api
    #   - ./classlibrary:/app/classlibrary
    environment:
      - NODE_ID=2
      - OTHER_NODES=1,http://node1:5000;3,http://node3:5000
      - NODE_INTERVAL=50
    command: dotnet watch --project raft-luris26.csproj
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - "5002:5000"
    networks:
      - raft_network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app/api
    # user: 1000:100
    # volumes:
    #   - ./api:/app/api
    #   - ./classlibrary:/app/classlibrary
    environment:
      - NODE_ID=3
      - OTHER_NODES=1,http://node1:5000;2,http://node2:5000
      - NODE_INTERVAL=50
    command: dotnet watch --project raft-luris26.csproj
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - "5003:5000"
    networks:
      - raft_network
  
  client:
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app
    # user: 1000:100
    networks:
      - raft_network
    depends_on:
      - node1
      - node2
      - node3
    # volumes:
    #   - ./raftClient:/app/raftClient
    #   - ./classlibrary:/app/classlibrary
    environment:
      - NODE_URL=http://node1:5000,http://node2:5000,http://node3:5000
    command: dotnet watch --project raftClient
    ports:
      - "5004:5000"  
networks:
  raft_network:
    driver: bridge